# Generated by Django 4.0.1 on 2022-05-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ifsc', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('relate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atm.bankname')),
            ],
        ),
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=2, max_digits=9)),
                ('relate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atm.bankname')),
            ],
        ),
    ]
