# Generated by Django 4.0.1 on 2022-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userid',
            field=models.CharField(default=11, max_length=12),
            preserve_default=False,
        ),
    ]
