# Generated by Django 4.0.1 on 2022-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_users_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='location',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
